### ISSUE TITLE
Add Immutable (tombstone) Lattices

### ISSUE THREAD

**Issue by jhellerstein** [ucbrise/LatticeFlow#11]

**Comment by mwhittaker** [comment]
What is a tombstone lattice? Do you just mean a set (e.g. integers) with an additional tombstone element that is greater than all other elements? Something like this Hasse diagram?

```
          top
        /  |  \
...   -1   0   1   ...
```

**Comment by jhellerstein** [comment]
I am thinking of it as a `std::pair<T, bool>` for any type `T` (need not be a lattice). The diagram you drew is the integer example. For small domains (e.g. `bool`) there may be more efficient implementations, in which case we might in principle want an abstraction of the lattice with the `std::pair` subclass as a common implementation. Note that tombstone lattices are a bit more expressive than immutables (consts) in that they can be marked deleted...

**Comment by mwhittaker** [comment]
How do you merge two instances of `std::pair<T, bool>`?

**Comment by jhellerstein** [comment]
Good question. If they agree on the first field, it's simply the `or` of the second. If they don't agree ... various options come to mind:
- One option is that if they don't agree on the first field, they merge to top. That is, "update" is the same semantics as "delete".
- A second option is to require an "ErrorState" lattice in the first field, which is a lattice consisting of any domain of incomparable values, a top value "err", and merge of any two distinct values is "err".  In that case, "update" is distinguishable from "delete".
- A simpler option is to punt on this, and only implement tombstoned `MapLattice`s (which use the map to enforce the "agree on the first field" part).

**Comment by mwhittaker** [comment]
I think the last option is simplest and cleanest. A tombstoned set of elements from domain `X` can be implemented as a MapLattice from `X` to a boolean lattice. I'll implement something like this.
