### ISSUE TITLE
Toolchain documentation

### ISSUE THREAD

**Issue by jhellerstein** [ucbrise/LatticeFlow#14]
Would be good to have Readmes or wiki pages on our tools and standards
- directory hierarchy rationale
- agreed-upon linters and configuration (pref. with plugins for editors like Sublime etc)
- CI instructions
- any coding conventions not checkable by linters
- policies on inclusion of 3rd-party libraries

**Comment by mwhittaker** [comment]
A handful of RISE Lab folks met the other day to talk about standardizing this kind of stuff. We started a [C++ project template](https://github.com/ucbrise/cpp_project_template) which will hopefully have all this kind of stuff documented.
